export const PERMISSIONS = {
  // Dashboard access
  VIEW_OVERVIEW: "view_overview",
  VIEW_LEADS: "view_leads",
  VIEW_PROJECTS: "view_projects",
  VIEW_CLIENT_STORIES: "view_client_stories",
  VIEW_BLOG: "view_blog",
  VIEW_CASE_STUDIES: "view_case_studies",
  VIEW_INDUSTRY_NEWS: "view_industry_news",
  VIEW_MEDIA_LIBRARY: "view_media_library",
  VIEW_EMAIL_LOGS: "view_email_logs",
  VIEW_SETTINGS: "view_settings",

  // Edit permissions
  EDIT_LEADS: "edit_leads",
  EDIT_PROJECTS: "edit_projects",
  EDIT_CLIENT_STORIES: "edit_client_stories",
  EDIT_BLOG: "edit_blog",
  EDIT_CASE_STUDIES: "edit_case_studies",
  EDIT_INDUSTRY_NEWS: "edit_industry_news",
  EDIT_MEDIA_LIBRARY: "edit_media_library",

  // Admin permissions
  MANAGE_USERS: "manage_users",
  MANAGE_ROLES: "manage_roles",
  MANAGE_SETTINGS: "manage_settings"
};

export const ROLE_PERMISSIONS = {
  admin: Object.values(PERMISSIONS),
  editor: [
    PERMISSIONS.VIEW_OVERVIEW,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_CLIENT_STORIES,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.VIEW_CASE_STUDIES,
    PERMISSIONS.VIEW_INDUSTRY_NEWS,
    PERMISSIONS.VIEW_MEDIA_LIBRARY,
    PERMISSIONS.VIEW_EMAIL_LOGS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_LEADS,
    PERMISSIONS.EDIT_PROJECTS,
    PERMISSIONS.EDIT_CLIENT_STORIES,
    PERMISSIONS.EDIT_BLOG,
    PERMISSIONS.EDIT_CASE_STUDIES,
    PERMISSIONS.EDIT_INDUSTRY_NEWS,
    PERMISSIONS.EDIT_MEDIA_LIBRARY
  ],
  viewer: [
    PERMISSIONS.VIEW_OVERVIEW,
    PERMISSIONS.VIEW_LEADS,
    PERMISSIONS.VIEW_PROJECTS,
    PERMISSIONS.VIEW_CLIENT_STORIES,
    PERMISSIONS.VIEW_BLOG,
    PERMISSIONS.VIEW_CASE_STUDIES,
    PERMISSIONS.VIEW_INDUSTRY_NEWS,
    PERMISSIONS.VIEW_MEDIA_LIBRARY,
    PERMISSIONS.VIEW_EMAIL_LOGS,
    PERMISSIONS.VIEW_SETTINGS
  ]
};
